make clean && make
kubectl apply -f ns.yaml
kubectl apply -f pizza-crd.yaml
kubectl apply -f topping-crd.yaml
kubectl apply -f sa.yaml
kubectl apply -f rbac.yaml
kubectl apply -f rbac-bind.yaml
kubectl apply -f service.yaml
kubectl apply -f serving-cert-secret.yaml
kubectl apply -f deployment.yaml
kubectl apply -f validatingadmissionregistration.yaml
kubectl apply -f mutatingadmissionregistration.yaml
